In [33]:
import numpy as np

In [34]:
lista = np.zeros_like([2,3,4,5,6,7])
lista

array([0, 0, 0, 0, 0, 0])

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
lista = np.array([2,4,5,6,2,66,13,18,12,76,7,8])
print(lista.dtype)
lista

int64


array([ 2,  4,  5,  6,  2, 66, 13, 18, 12, 76,  7,  8])

In [37]:
lista.shape

(12,)

In [38]:
lista.reshape((2,6))

array([[ 2,  4,  5,  6,  2, 66],
       [13, 18, 12, 76,  7,  8]])

In [39]:
lista = np.append(lista, [23, 24, 6, 53,33, 13])
lista

array([ 2,  4,  5,  6,  2, 66, 13, 18, 12, 76,  7,  8, 23, 24,  6, 53, 33,
       13])

In [40]:
np.where(lista == 13)

(array([ 6, 17]),)

In [41]:
np.shape(lista)

(18,)

In [42]:
lista.reshape((6,3))

array([[ 2,  4,  5],
       [ 6,  2, 66],
       [13, 18, 12],
       [76,  7,  8],
       [23, 24,  6],
       [53, 33, 13]])

In [43]:
lista_1 = np.array([2,3,4,5,6])
lista_2 = np.array([5,23,32,32,53])

In [44]:
lista_1*lista_1 

array([ 4,  9, 16, 25, 36])

In [45]:
lista_2/(lista_1 ** 2)

array([1.25      , 2.55555556, 2.        , 1.28      , 1.47222222])

In [46]:
lista_2 = np.arange(30)
lista_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
np.reshape(lista_2, (6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [51]:
dato = np.arange(30)
np.array(dato, dtype= np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [52]:
dato= np.array(dato, dtype= np.str_)
dato

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29'], dtype='<U21')

In [53]:
dato.dtype

dtype('<U21')

In [54]:
dato = np.reshape(dato,(5,3,2))
dato

array([[['0', '1'],
        ['2', '3'],
        ['4', '5']],

       [['6', '7'],
        ['8', '9'],
        ['10', '11']],

       [['12', '13'],
        ['14', '15'],
        ['16', '17']],

       [['18', '19'],
        ['20', '21'],
        ['22', '23']],

       [['24', '25'],
        ['26', '27'],
        ['28', '29']]], dtype='<U21')

In [55]:
dato.ndim

3

In [56]:
dato.shape

(5, 3, 2)

In [57]:
dato.size

30

In [58]:
array = np.array([3,5,7,9], dtype = np.float32)

In [59]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
array.reshape((2,2,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [61]:
array_1 = np.empty(10)
array_1 = array_1.reshape((5,2))
array_2 = np.empty(10)
array_2 = array_2.reshape((5,2))
array_3 = np.empty(10)
array_3 = array_3.reshape((5,2))

In [62]:
array_2

array([[nan,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [63]:
array_1

array([[nan,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [64]:
array_3

array([[nan,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [65]:
nombre = np.array(['Eduardo', 'Jorge', 'Miguel', 'Ignacio', 'Pedro'])
nombre

array(['Eduardo', 'Jorge', 'Miguel', 'Ignacio', 'Pedro'], dtype='<U7')

In [66]:
edad = np.array([18, 20, 42, 21, 14])
edad

array([18, 20, 42, 21, 14])

In [67]:
dia = np.array([23, 14, 12, 25, 21])
dia

array([23, 14, 12, 25, 21])

In [68]:
print(nombre[(edad>20) | (dia<24)])

['Eduardo' 'Jorge' 'Miguel' 'Ignacio' 'Pedro']


In [69]:
np.stack((nombre, edad, dia), axis=1)

array([['Eduardo', '18', '23'],
       ['Jorge', '20', '14'],
       ['Miguel', '42', '12'],
       ['Ignacio', '21', '25'],
       ['Pedro', '14', '21']], dtype='<U21')

In [70]:
array = np.arange(30)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
array= array.reshape(6,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [72]:
separado = np.split(array, 6)
separado

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]])]

In [73]:
peso_y_altura= np.array([[87, 1.61],
                         [65, 1.74],
                         [60, 1.65],
                         [78, 1.67],
                         [76, 1.78]])
peso_y_altura

array([[87.  ,  1.61],
       [65.  ,  1.74],
       [60.  ,  1.65],
       [78.  ,  1.67],
       [76.  ,  1.78]])

In [74]:
peso_y_altura.min(axis=0)

array([60.  ,  1.61])

In [75]:
peso_y_altura.max(axis=0)

array([87.  ,  1.78])

In [76]:
peso_y_altura.argmax(axis=0)

array([0, 4])

In [77]:
peso_y_altura.argmin(axis=0)

array([2, 0])

In [78]:
peso_y_altura.mean(axis=0)

array([73.2 ,  1.69])

In [79]:
peso_y_altura.sum(axis=0)

array([366.  ,   8.45])