In [1]:
list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
list_C = []
for element in list_1:
    if element[0] == "c":
        list_C.append(element.upper())
print(list_C)

['CUATRO', 'CINCO']


In [2]:
def mi_funcion(lista, inicial, a_mayuscula):
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return list_out

list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
print(mi_funcion(list_1, "c", True))
print(mi_funcion(list_1, "u", False))
print(mi_funcion(list_1, "t", True))

['CUATRO', 'CINCO']
['uno']
['TRES', 'TREINTA']


In [3]:
def mi_funcion(lista, inicial, a_mayuscula = True):
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return list_out

list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
print(mi_funcion(list_1, "c"))
print(mi_funcion(list_1, "u", False))
print(mi_funcion(list_1, "t", True))

['CUATRO', 'CINCO']
['uno']
['TRES', 'TREINTA']


In [4]:
list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
mi_funcion(inicial = "c", lista = list_1)

['CUATRO', 'CINCO']

In [5]:
def mi_funcion(lista, inicial, a_mayuscula = True):
    list_out = []
    for element in lista:
        if element[0] == inicial:
            if a_mayuscula:
                list_out.append(element.upper())
            else:
                list_out.append(element.lower())
    return (len(list_out), list_out)

list_1 = ["uno", "dos", "tres", "cuatro", "cinco", "treinta"]
num_elementos, elementos = mi_funcion(list_1,"c")

for i in range(0, num_elementos):
    print(elementos[i])

CUATRO
CINCO


In [6]:
import numpy
array = numpy.array([[1,2], [3,4]])
mean = numpy.mean(array)
print (array)
print (mean)

[[1 2]
 [3 4]]
2.5


In [7]:
from numpy import *
array = array([[1,2], [3,4]])
media = mean(array)
print (array)
print (media)

[[1 2]
 [3 4]]
2.5


In [8]:
from numpy import array, mean
array = array([[1, 2], [3, 4]])
media2 = mean(array)
print(array)
print(media2)

[[1 2]
 [3 4]]
2.5


In [9]:
from numpy import array as array_de_numpy
array = array_de_numpy([[1, 2], [3, 4]])
print (array)

[[1 2]
 [3 4]]
