In [1]:
from pandas import Series, DataFrame
import pandas as pd

### Series

In [4]:
obj = Series([5,-2,3,9])
obj

0    5
1   -2
2    3
3    9
dtype: int64

In [5]:
obj.values

array([ 5, -2,  3,  9])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = Series([4,7,-5,3], index = ['b','d','a','c'])
obj2

b    4
d    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['b', 'd', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

np.int64(-5)

In [12]:
obj2['d'] = 6
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2

b    4
d    6
a   -5
c    3
dtype: int64

In [14]:
obj2[obj2>0]

b    4
d    6
c    3
dtype: int64

In [15]:
obj2*2

b     8
d    12
a   -10
c     6
dtype: int64

In [17]:
import numpy as np
np.exp(obj2)

b     54.598150
d    403.428793
a      0.006738
c     20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon':16000, 'Utah':5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [27]:
obj4.name = 'population'
obj4.index.name ='state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [29]:
obj

0    5
1   -2
2    3
3    9
d    6
dtype: int64

In [30]:
obj.index = ['Ivan','David','Gomez','Pariona','Juan']
obj

Ivan       5
David     -2
Gomez      3
Pariona    9
Juan       6
dtype: int64

### DataFrame

In [32]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year': [2000,2001,2002,2002,2002],
        'pop': [1.5,1.7,3.6,2.4,2.9]}

frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2002  2.4
4  Nevada  2002  2.9

In [33]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2002  Nevada  2.4
4  2002  Nevada  2.9

In [35]:
frame2 = DataFrame(data, columns=['year','state','pop','debt'],
                   index = ['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2002  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [36]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [37]:
frame2.year

one      2000
two      2001
three    2002
four     2002
five     2002
Name: year, dtype: int64

In [41]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2002  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [44]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2002  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [45]:
val = Series([-1.2,-1.5,-1.7], index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2002  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [49]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2002  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [50]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2002  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
pop = {'Nevada': {2001:2.4, 2002:2.9},
       'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

In [60]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [55]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [56]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [57]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [62]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [63]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [64]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2002, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Index Objects

In [67]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [68]:
index[1:]

Index(['b', 'c'], dtype='object')

In [69]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [70]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [71]:
'Ohio' in frame3.columns

True

In [72]:
2003 in frame3.index

False

| Método         | Descripción |
|----------------|-------------|
| `append`       | Concatena con otros objetos `Index`, produciendo un nuevo `Index`. |
| `diff`         | Calcula la diferencia entre conjuntos como un `Index`. |
| `intersection` | Calcula la intersección de conjuntos. |
| `union`        | Calcula la unión de conjuntos. |
| `isin`         | Devuelve un array booleano que indica si cada valor está contenido en la colección pasada. |
| `delete`       | Devuelve un nuevo `Index` con el elemento en la posición `i` eliminado. |
| `drop`         | Devuelve un nuevo `Index` eliminando los valores especificados. |
| `insert`       | Devuelve un nuevo `Index` insertando un elemento en la posición `i`. |
| `is_monotonic` | Devuelve `True` si cada elemento es mayor o igual al anterior. |
| `is_unique`    | Devuelve `True` si el `Index` no tiene valores duplicados. |
| `unique`       | Devuelve un array con los valores únicos del `Index`. |

### Essential Functionality

In [75]:
obj = Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [77]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [78]:
obj.reindex(['a','b','c','d','e'], fill_value = 0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [80]:
obj3 = Series(['blue','purple','yellow'], index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [81]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [83]:
frame = DataFrame(np.arange(9).reshape((3,3)), index = ['a','c','d'],
                  columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [84]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [86]:
states = ['Texas','Utah','California']
frame.reindex(columns =states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [88]:
frame.reindex(index=['a','b','c','d'], method='ffill')
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### Dropping entries from an axis

In [91]:
obj = Series(np.arange(5.), index=['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [93]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [94]:
data = DataFrame(np.arange(16).reshape(4,4),
                 index=['Lima','Huancayo','Arequipa','Ayacucho'],
                 columns=['one','two','three','four'])
data.drop(['Huancayo','Lima'])

one  two  three  four
Arequipa    8    9     10    11
Ayacucho   12   13     14    15

In [96]:
data.drop(['two'], axis=1)

one  three  four
Lima        0      2     3
Huancayo    4      6     7
Arequipa    8     10    11
Ayacucho   12     14    15

In [101]:
data.drop(['two','four'], axis=1)

one  three
Lima        0      2
Huancayo    4      6
Arequipa    8     10
Ayacucho   12     14

### Indexing, selection and filtering

In [103]:
obj = Series(np.arange(4.), index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [104]:
obj['b']

np.float64(1.0)

In [105]:
obj[1]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [106]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [107]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [108]:
obj[[1,3]]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [109]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [111]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [112]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [114]:
data = DataFrame(np.arange(16).reshape(4,4),
                 index=['Lima','Huancayo','Arequipa','Ayacucho'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Lima        0    1      2     3
Huancayo    4    5      6     7
Arequipa    8    9     10    11
Ayacucho   12   13     14    15

In [126]:
data['two']

Lima         1
Huancayo     5
Arequipa     9
Ayacucho    13
Name: two, dtype: int64

In [127]:
data[['three','one']]

three  one
Lima          2    0
Huancayo      6    4
Arequipa     10    8
Ayacucho     14   12

In [128]:
data[:2]

one  two  three  four
Lima        0    1      2     3
Huancayo    4    5      6     7

In [129]:
data[data['three'] > 5]

one  two  three  four
Huancayo    4    5      6     7
Arequipa    8    9     10    11
Ayacucho   12   13     14    15

In [130]:
data < 5

one    two  three   four
Lima       True   True   True   True
Huancayo   True  False  False  False
Arequipa  False  False  False  False
Ayacucho  False  False  False  False

In [131]:
data[data < 5]  = 0
data

one  two  three  four
Lima        0    0      0     0
Huancayo    0    5      6     7
Arequipa    8    9     10    11
Ayacucho   12   13     14    15

In [134]:
data.loc['Huancayo', ['two', 'three']]

two      5
three    6
Name: Huancayo, dtype: int64

In [139]:
s1 =  Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])
s2 =  Series([-2.1,3-6,-1.5,4,3.1], index = ['a','c','e','f','g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [140]:
s2

a   -2.1
c   -3.0
e   -1.5
f    4.0
g    3.1
dtype: float64

In [142]:
s1 + s2

a    5.2
c   -5.5
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [146]:
df1 = DataFrame(np.arange(9.).reshape(3,3), columns=list('bcd'),
                index=['Ohio', 'Texas','Colorado'])
df2 = DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [147]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [148]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [150]:
df1 = DataFrame(np.arange(12.).reshape(3,4), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape(4,5), columns=list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [151]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [152]:
df1 +  df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [153]:
df1.reindex(columns=df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

In [154]:
arr = np.arange(12.).reshape(3,4)
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [155]:
arr[0]

array([0., 1., 2., 3.])

In [156]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [162]:
frame = DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [163]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [164]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [165]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [166]:
series2 = Series(range(3), index=['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [167]:
series3 = frame['d']

In [168]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [169]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [170]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping

In [171]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'),
                  index = ['Utah','Ohio','Texas', 'Oregon'])
frame

b         d         e
Utah   -1.997460  0.984495 -2.555558
Ohio   -0.715481  0.829393  2.372721
Texas  -0.391630  1.235392 -0.642120
Oregon -0.015812  0.145762  1.380011

In [172]:
np.abs(frame)

b         d         e
Utah    1.997460  0.984495  2.555558
Ohio    0.715481  0.829393  2.372721
Texas   0.391630  1.235392  0.642120
Oregon  0.015812  0.145762  1.380011

In [173]:
f = lambda x : x.max() - x.min()
frame.apply(f)

b    1.981649
d    1.089629
e    4.928279
dtype: float64

In [174]:
frame.apply(f, axis=1)

Utah      3.540053
Ohio      3.088202
Texas     1.877512
Oregon    1.395823
dtype: float64

In [176]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -1.997460  0.145762 -2.555558
max -0.015812  1.235392  2.372721

### Sorting and ranking

In [177]:
obj = Series(range(4), index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [181]:
frame = DataFrame(np.arange(8).reshape(2,4), index=['three', 'one'],
                  columns=['d','a','b','c'])

In [182]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [184]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [185]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [188]:
obj = Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [189]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [190]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [192]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

### Summarizing and Computing Descriptive Statistics

In [197]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index = ['a','b', 'c', 'd'],
               columns = ['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [198]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [199]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [200]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [201]:
df.idxmax()

one    b
two    d
dtype: object

In [202]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [203]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [205]:
obj = Series(['a','a','b','c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [206]:
df.count()

one    3
two    2
dtype: int64

| Método              | Descripción |
|---------------------|-------------|
| `count`             | Número de valores no nulos (`non-NA`). |
| `describe`          | Calcula un conjunto de estadísticas resumen para Series o para cada columna de un DataFrame. |
| `min`, `max`        | Calcula el valor mínimo y máximo. |
| `argmin`, `argmax`  | Devuelve la posición (índice entero) del valor mínimo o máximo, respectivamente. |
| `idxmin`, `idxmax`  | Devuelve la etiqueta del índice donde se encuentra el valor mínimo o máximo, respectivamente. |
| `quantile`          | Calcula un cuantil de la muestra, en el rango de 0 a 1. |
| `sum`               | Suma de los valores. |
| `mean`              | Media (promedio) de los valores. |
| `median`            | Mediana aritmética (cuantil del 50%). |
| `mad`               | Desviación absoluta media respecto a la media. |
| `var`               | Varianza muestral de los valores. |
| `std`               | Desviación estándar muestral de los valores. |
| `skew`              | Asimetría muestral (tercer momento). |
| `kurt`              | Curtosis muestral (cuarto momento). |
| `cumsum`            | Suma acumulativa de los valores. |
| `cummin`, `cummax`  | Mínimo o máximo acumulativo, respectivamente. |
| `cumprod`           | Producto acumulativo de los valores. |
| `diff`              | Calcula la diferencia aritmética entre elementos adyacentes (útil para series temporales). |
| `pct_change`        | Calcula los cambios porcentuales entre elementos consecutivos. |


### Correlation and Covariance

In [213]:
data = {
    'math': [80, 90, 70, 85, 95],
    'physics': [78, 88, 68, 83, 93],
    'literature': [60, 65, 70, 62, 58]
}

df = pd.DataFrame(data)
print(df)


   math  physics  literature
0    80       78          60
1    90       88          65
2    70       68          70
3    85       83          62
4    95       93          58


In [215]:
df.corr()

math   physics  literature
math        1.000000  1.000000   -0.720446
physics     1.000000  1.000000   -0.720446
literature -0.720446 -0.720446    1.000000

In [214]:
df.cov()

math  physics  literature
math        92.5     92.5       -32.5
physics     92.5     92.5       -32.5
literature -32.5    -32.5        22.0

### Unique Values, Value Counts, and Membership

In [216]:
obj = Series(['c','a','d','a','a','b','b','c','c'])

In [217]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [220]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [221]:
pd.value_counts(obj.values, sort=False)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\3084372382.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [222]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [223]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [225]:
data = DataFrame({'Qu1': [1,3,4,3,4],
                  'Qu2': [2,3,1,2,3],
                  'Qu3': [1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [226]:
result = data.apply(pd.value_counts).fillna(0)
result

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\1382616601.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

### Handling Missing Data

In [227]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [228]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data

In [229]:
from numpy import nan as NA
data = Series([1,NA,3.5,NA,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [230]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA],
                [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [231]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [232]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [233]:
data.dropna(how='all', axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [234]:
df = DataFrame(np.random.rand(7,3))
df.loc[:4, 1] = NA; df.loc[:2,2] = NA
df

0         1         2
0  0.566660       NaN       NaN
1  0.978943       NaN       NaN
2  0.374643       NaN       NaN
3  0.734853       NaN  0.306952
4  0.557920       NaN  0.154235
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

In [235]:
df.dropna(thresh=3)

0         1         2
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

### Filling in Missing Data

In [236]:
df.fillna(0)

0         1         2
0  0.566660  0.000000  0.000000
1  0.978943  0.000000  0.000000
2  0.374643  0.000000  0.000000
3  0.734853  0.000000  0.306952
4  0.557920  0.000000  0.154235
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

In [237]:
df.fillna({1:0.5, 3:-1})

0         1         2
0  0.566660  0.500000       NaN
1  0.978943  0.500000       NaN
2  0.374643  0.500000       NaN
3  0.734853  0.500000  0.306952
4  0.557920  0.500000  0.154235
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

In [238]:
df.fillna(method='bfill')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')


0         1         2
0  0.566660  0.503305  0.306952
1  0.978943  0.503305  0.306952
2  0.374643  0.503305  0.306952
3  0.734853  0.503305  0.306952
4  0.557920  0.503305  0.154235
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

In [239]:
df.fillna(method='ffill')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0         1         2
0  0.566660       NaN       NaN
1  0.978943       NaN       NaN
2  0.374643       NaN       NaN
3  0.734853       NaN  0.306952
4  0.557920       NaN  0.154235
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

In [241]:
df.fillna(method='bfill', limit=2)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24720\1201028645.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', limit=2)


0         1         2
0  0.566660       NaN       NaN
1  0.978943       NaN  0.306952
2  0.374643       NaN  0.306952
3  0.734853  0.503305  0.306952
4  0.557920  0.503305  0.154235
5  0.093715  0.503305  0.888469
6  0.150255  0.545798  0.244827

In [242]:
data = Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [245]:
 data = Series(np.random.randn(10),
        index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
        [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
 data

a  1    0.159029
   2   -1.542335
   3    1.367699
b  1    1.414584
   2   -0.126195
   3    1.207986
c  1   -0.256770
   2    1.441510
d  2    0.898791
   3   -0.135133
dtype: float64

In [246]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [247]:
data['b']

1    1.414584
2   -0.126195
3    1.207986
dtype: float64

In [248]:
data['b':'c']

b  1    1.414584
   2   -0.126195
   3    1.207986
c  1   -0.256770
   2    1.441510
dtype: float64

In [249]:
data.loc[['b','d']]

b  1    1.414584
   2   -0.126195
   3    1.207986
d  2    0.898791
   3   -0.135133
dtype: float64

In [250]:
data[:,2]

a   -1.542335
b   -0.126195
c    1.441510
d    0.898791
dtype: float64

In [251]:
data.unstack()

1         2         3
a  0.159029 -1.542335  1.367699
b  1.414584 -0.126195  1.207986
c -0.256770  1.441510       NaN
d       NaN  0.898791 -0.135133

In [252]:
data.unstack().stack()

a  1    0.159029
   2   -1.542335
   3    1.367699
b  1    1.414584
   2   -0.126195
   3    1.207986
c  1   -0.256770
   2    1.441510
d  2    0.898791
   3   -0.135133
dtype: float64

In [254]:
 frame = DataFrame(np.arange(12).reshape((4, 3)),
        index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
        columns=[['Ohio', 'Ohio', 'Colorado'],
        ['Green', 'Red', 'Green']])
 frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [256]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
        'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
        'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3