In [29]:
import numpy as np

In [30]:
# Especificando dimensiones
array_vacio = np.empty((3, 2), dtype= np.str_)
array_vacio

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [31]:
# Copiando dimensiones y tipo desde otra estructura
array_vacio_copia = np.empty_like([1, 2, 3, 4, 5])
array_vacio_copia

array([4607182418800017408, 4611686018427387904, 4613937818241073152,
       4616189618054758400, 4617315517961601024])

In [32]:
# Especificando dimensiones
array_unos = np.ones((3, 2))
array_unos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
# Copiando dimensiones y tipo desde otra estructura
array_unos_copia = np.ones_like([1, 2, 3, 4, 5])
array_unos_copia

array([1, 1, 1, 1, 1])

In [34]:
# Especificando dimensiones
array_ceros = np.zeros((3, 2))
array_ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
# Copiando dimensiones y tipo desde otra estructura
array_ceros_copia = np.zeros_like([1, 2, 3, 4, 5])
array_ceros_copia

array([0, 0, 0, 0, 0])

In [36]:
array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# Cuadrada con unos en la diagonal principal
array_identidad = np.eye(4)
array_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# Cuadrada con unos en la diagonal específicada
array_con_segunda_identidad = np.eye(4, k = 1)
array_con_segunda_identidad

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [39]:
# Cuadrada con unos en la diagonal específicada
array_no_identidad = np.eye(4, k = -1)
array_no_identidad

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
array_secuencia_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# Dos parámetros: desde  el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(5, 10)
array_secuencia_2

array([5, 6, 7, 8, 9])

In [42]:
# Tres parámetros: desde  el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
# Unidimensional
array_basico = np.array([1, 2, 3, 4, 5])
type(array_basico)

numpy.ndarray

In [44]:
# Multidimensional
array_basico_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
array_inicial_enteros = np.array([1, 2, 3, 4, 5], dtype= np.int32)
array_inicial_enteros

array([1, 2, 3, 4, 5], dtype=int32)

In [46]:
array_float = np.asarray(array_inicial_enteros, dtype= np.float64)
array_float

array([1., 2., 3., 4., 5.])

In [47]:
array_strings = np.asarray (array_float, dtype= np.str_)
array_strings

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

In [48]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [49]:
# Tipo de dato (único)
array.dtype

dtype('int64')

In [50]:
# Número de dimensiones
array.ndim

2

In [51]:
# Forma/Dimensiones
array.shape

(3, 4)

In [52]:
# Número total de elementos
array.size

12

In [53]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [54]:
# Suma
array + 5

array([ 6.,  7.,  8.,  9., 10., 11.])

In [55]:
# Resta
array - 2

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [56]:
# Multiplicación
array * 3

array([ 3.,  6.,  9., 12., 15., 18.])

In [57]:
# División
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [58]:
# División entera 
array // 2

array([0., 1., 1., 2., 2., 3.])

In [59]:
# Potencia
array ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [60]:
# Asignación con operador
array += 1
array

array([2., 3., 4., 5., 6., 7.])

In [61]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [62]:
# Suma (elemento a elemento)
array + array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [63]:
# Resta (elemento a elemento)
array - array

array([0., 0., 0., 0., 0., 0.])

In [64]:
# Multiplicación (elemento a elemento)
array * array

array([ 1.,  4.,  9., 16., 25., 36.])

In [65]:
# División (elemento a elemento)
array / array

array([1., 1., 1., 1., 1., 1.])

In [66]:
# Asignación con operador
array += array
array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [67]:
# Suma de ndarrays de distinto tamaño
array1 = np.array([1, 2, 3, 4, 5, 6])
array + array1

array([ 3.,  6.,  9., 12., 15., 18.])

In [68]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
# Indexación con primer parámetro
array[2]

np.int64(3)

In [70]:
# Indexación con primer y segundo parámetro
array [2:5]

array([3, 4, 5])

In [71]:
# Indexación con tercer parámetro
array[::2]

array([1, 3, 5, 7, 9])

In [72]:
# Indexación con negativos
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [73]:
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [74]:
# Forma de la matriz
array.shape

(2, 2, 4)

In [75]:
# Indexación recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [76]:
# Indexación recursiva segundo nivel
array[1][0]

array([ 9, 10, 11, 12])

In [77]:
# Indexación recursiva tercer nivel
array[1][0][3]

np.int64(12)

In [78]:
# Indexación con comas segundo nivel
array[1, 0]

array([ 9, 10, 11, 12])

In [79]:
# Indexación con comas tercer nivel
array[1, 0, 3]

np.int64(12)

In [80]:
# Indexación recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [81]:
# Indexación recursiva tercer nivel con slice de índice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

In [82]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [83]:
# Modificación de una posición
array[0][1] = 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [84]:
# Modificación de un slice
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

In [85]:
personas = np.array(['Miguel', 'Pedro', 'Juan', 'Miguel'])
personas

array(['Miguel', 'Pedro', 'Juan', 'Miguel'], dtype='<U6')

In [86]:
datos = np.random.randn(4,4)
datos

array([[-2.50132880e+00, -7.58473240e-04, -1.50333382e+00,
        -7.26639831e-01],
       [-1.06575610e+00, -1.52052163e+00, -1.39043037e+00,
        -1.16269435e+00],
       [ 6.70144593e-02,  9.59332676e-01, -6.64520316e-01,
        -1.50922162e+00],
       [-1.40263980e+00,  5.73391226e-01,  1.19582711e+00,
         6.50914573e-01]])

In [87]:
# Indexación/slicing booleano sobre valores
datos[datos < 0]

array([-2.50132880e+00, -7.58473240e-04, -1.50333382e+00, -7.26639831e-01,
       -1.06575610e+00, -1.52052163e+00, -1.39043037e+00, -1.16269435e+00,
       -6.64520316e-01, -1.50922162e+00, -1.40263980e+00])

In [88]:
# Máscara booleana
personas == 'Miguel'

array([ True, False, False,  True])

In [89]:
# Indexación/slicing medinate máscara
datos[personas == 'Miguel']

array([[-2.50132880e+00, -7.58473240e-04, -1.50333382e+00,
        -7.26639831e-01],
       [-1.40263980e+00,  5.73391226e-01,  1.19582711e+00,
         6.50914573e-01]])

In [90]:
# Indexación/slicing mediante máscara y básico combinado
datos[personas == 'Miguel', ::2]

array([[-2.5013288 , -1.50333382],
       [-1.4026398 ,  1.19582711]])

In [91]:
# Indexación/slicing mediante máscara negativo por operador
datos[personas != 'Miguel']

array([[-1.0657561 , -1.52052163, -1.39043037, -1.16269435],
       [ 0.06701446,  0.95933268, -0.66452032, -1.50922162]])

In [92]:
# Indexación/slicing mediante máscara negativo por signo
datos[~(personas == 'Miguel')]

array([[-1.0657561 , -1.52052163, -1.39043037, -1.16269435],
       [ 0.06701446,  0.95933268, -0.66452032, -1.50922162]])

In [93]:
array = np.random.randn(7,4)
array

array([[ 0.52542595,  0.85884688, -0.25231274, -0.25655406],
       [ 0.98971202, -1.36047378,  0.07808679, -0.32329647],
       [-0.3578264 , -0.18329925,  0.02755318,  0.1621434 ],
       [ 1.35306033,  0.84726952, -0.14903619,  2.56864735],
       [-0.30421538, -0.42961014,  0.86600633,  0.52350892],
       [-1.09005372, -0.02374682, -0.11273686, -1.10688302],
       [ 1.82732143,  0.42505012,  0.30128515, -0.5098422 ]])

In [94]:
# Eliminación de valores negativos mediante slicing
array[array <0] = 0
array

array([[0.52542595, 0.85884688, 0.        , 0.        ],
       [0.98971202, 0.        , 0.07808679, 0.        ],
       [0.        , 0.        , 0.02755318, 0.1621434 ],
       [1.35306033, 0.84726952, 0.        , 2.56864735],
       [0.        , 0.        , 0.86600633, 0.52350892],
       [0.        , 0.        , 0.        , 0.        ],
       [1.82732143, 0.42505012, 0.30128515, 0.        ]])

In [95]:
array = np.empty((8,4))
for i in range(8):
    array[i] = i
array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [96]:
# Indexación/slicing de un conjunto (arbitrario) de elementos
array[[2, 5]]

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [97]:
# Indexación/slicing de un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [98]:
array = np.arange(32).reshape((8,4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [99]:
# Indexación/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [100]:
# Indexación/slicing con una secuencia de varios niveles (región resultante)
array[[1, 5, 7, 2]] [[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [101]:
array = np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
# Modificación de ejes/dimensiones
array2 = array.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
# Trasposición de ejes/dimensiones
array2.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [104]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [105]:
array2 = np.arange(15, 30).reshape(3, 5)
array2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [106]:
# Concatenación horizontal
np.hstack((array1, array2))

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [107]:
# Concatenación horizontal
np.vstack((array1, array2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [108]:
array = np.arange(16).reshape(4, 4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
# División simétrica por columnas
np.hsplit(array, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [110]:
# División simétrica por filas
np.vsplit(array, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [111]:
# División no simétrica
np.split(array, [2, 3], axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [112]:
array.sum(axis=0)

array([24, 28, 32, 36])