In [1]:
import numpy as np

- **abs, fabs:** Valor absoluto
- **sqrt:** Raíz cuadrada (equivalente a array**0.5)
- **square:** Potencia al cuadrado (equivalente a array**2)
- **exp:** Potencia de e
- **log, log2, log10, log1p:** Logaritmos en distintas bases
- **sign:** Signo (+ = 1 /- = -1 / 0 = 0)
- **ceil:** Techo
- **floor:** Suelo
- **rint:** Redondo al entero más cercano
- **modf:** Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera
- **isnan:** Devuelve un array booleano indicando si el valor es NaN o no
- **isfinite, isinf:** Devuelve un array booleano indicando si el valor es finito o infinito
- **cos, cosh, sin, sinh, tan, tanh:** Funciones trigonométricas
- **arccos, arccosh, arcsin, arcsinh, arctan, arctanh:** Funciones trigonométricas inversas
- **logical_not:** Inverso booleano en todos los valores del array (equivalente a ~(array))

In [2]:
array = np.array([-1, 2, 3., -4.8, 5.7, 6.5])
np.abs(array)

array([1. , 2. , 3. , 4.8, 5.7, 6.5])

In [3]:
np.sqrt(array)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23548\1305867869.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array)


array([       nan, 1.41421356, 1.73205081,        nan, 2.38746728,
       2.54950976])

In [4]:
np.square(array)

array([ 1.  ,  4.  ,  9.  , 23.04, 32.49, 42.25])

In [5]:
np.exp(array)

array([3.67879441e-01, 7.38905610e+00, 2.00855369e+01, 8.22974705e-03,
       2.98867401e+02, 6.65141633e+02])

In [6]:
np.sign(array)

array([-1.,  1.,  1., -1.,  1.,  1.])

In [7]:
np.ceil(array)

array([-1.,  2.,  3., -4.,  6.,  7.])

- **add:** Adición de los elementos de los dos arrays (equivalente a array1 + array2)
- **subtract:** Resta de los elementos de los dos arrays (equivalente a array1 - array2)
- **multiply:** Multiplica los elementos de los dos arrays (equivale a array1 * array2)
- **divide, floor_divide:** Divide los elementos de los dos arrays (equivale a array1 / (o //) array2)
- **power:** Eleva los elementos del primer array a las potencias del segundo (equivalente a array1**array2)
- **maximum, fmax:** Calcula el máximo de los dos arrays (elemento a elemento) fmax ignora NaN
- **minimum, fmin:** Calcula el mínimo de los dos arrays (elemento a elemento) fmin ignora NaN
- **mod:** Calcula el resto de la división de los dos arrays (equivalente a array1 % array2)
- **greater, greater_equal, less, less_equal, not_equal:** Comparativas sobre los elementos de ambos ndarrays (elemento a elemento)
- **logical_and, logical_or:** Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento)

In [8]:
array1 = np.random.randn(5,5)
array1

array([[-0.3946433 ,  0.42225994, -0.28939241, -1.77950702, -1.49871538],
       [-0.52119306,  1.59778007,  0.7277566 ,  0.56064734, -0.2881683 ],
       [ 0.91394297, -0.59383781,  0.90862366, -0.30149954, -0.35164392],
       [-0.01268753,  0.1086001 ,  0.95845287,  0.94192515, -0.68595871],
       [ 0.95860489,  0.94858305,  0.5068459 ,  1.237839  ,  0.28447973]])

In [9]:
array2 = np.random.randn(5,5)
array2

array([[-0.48870103, -0.28210498,  0.30200056, -0.15826955, -0.48385084],
       [-0.29634003,  0.16091397, -1.14862479,  0.89565838,  0.77711896],
       [-0.94603571, -0.60533446,  1.75250084, -0.12023576,  1.73313062],
       [ 1.9100795 , -0.11513419,  1.74241852, -2.30408166,  0.78633692],
       [ 1.60987829, -0.67769065,  0.21563582,  1.92997179, -0.48774573]])

In [10]:
np.logical_and(array1, array2)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [11]:
np.divide(array1,array2)

array([[ 8.07535218e-01, -1.49681845e+00, -9.58251243e-01,
         1.12435213e+01,  3.09747399e+00],
       [ 1.75876700e+00,  9.92940584e+00, -6.33589495e-01,
         6.25961140e-01, -3.70816200e-01],
       [-9.66076603e-01,  9.81007761e-01,  5.18472595e-01,
         2.50756973e+00, -2.02895222e-01],
       [-6.64241006e-03, -9.43248053e-01,  5.50070410e-01,
        -4.08807192e-01, -8.72347081e-01],
       [ 5.95451780e-01, -1.39972869e+00,  2.35047169e+00,
         6.41376731e-01, -5.83254174e-01]])

In [12]:
np.floor_divide(array1,array2)

array([[ 0., -2., -1., 11.,  3.],
       [ 1.,  9., -1.,  0., -1.],
       [-1.,  0.,  0.,  2., -1.],
       [-1., -1.,  0., -1., -1.],
       [ 0., -2.,  2.,  0., -1.]])

In [13]:
array1 = np.random.randn(5,5)
array1

array([[-1.99580661,  0.1130353 ,  0.06153351, -0.75734572,  1.67748005],
       [ 0.28413778,  0.5060934 , -0.71884597, -0.18622846, -0.44161433],
       [-0.06271852,  0.51999825,  1.44703135,  0.5736031 , -1.21340847],
       [ 0.76105099, -0.27992305,  1.47599324, -1.41293754, -0.02524464],
       [-1.26874859,  1.54996405,  0.72028584,  0.98446179,  0.65285199]])

In [14]:
array2 = np.random.randn(5,5)
array2

array([[ 0.78621436, -0.53616526,  0.03252657,  0.17505754, -1.5042825 ],
       [ 0.01252362, -0.11708351, -1.44114422,  0.599949  ,  0.58773158],
       [ 0.78527237,  0.53195878, -0.95626345,  0.70997642, -0.30753797],
       [-1.58858267, -1.1292701 , -0.05980934, -0.81662038, -0.57719994],
       [-0.58738111, -0.02319338, -0.13448563, -2.14140819,  0.24450207]])

In [15]:
# Función condicional
np.where(array1 < array2, array1, array2)

array([[-1.99580661, -0.53616526,  0.03252657, -0.75734572, -1.5042825 ],
       [ 0.01252362, -0.11708351, -1.44114422, -0.18622846, -0.44161433],
       [-0.06271852,  0.51999825, -0.95626345,  0.5736031 , -1.21340847],
       [-1.58858267, -1.1292701 , -0.05980934, -1.41293754, -0.57719994],
       [-1.26874859, -0.02319338, -0.13448563, -2.14140819,  0.24450207]])

In [16]:
# Anidación de condiciones
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)

array([[ 0.        , -0.53616526,  0.03252657,  0.        , -1.5042825 ],
       [ 0.01252362, -0.11708351, -1.44114422,  0.        ,  0.        ],
       [ 0.        ,  0.51999825, -0.95626345,  0.5736031 ,  0.        ],
       [-1.58858267, -1.1292701 , -0.05980934,  0.        , -0.57719994],
       [ 0.        , -0.02319338, -0.13448563, -2.14140819,  0.24450207]])

- **sum:** Suma de elementos
- **mean:** Media aritmética de los elementos
- **median:** Mediana de los alementos
- **std:** Desviación estándar de los elementos
- **var:** Varianza de los elementos
- **min:** Valor mínimo de los elementos
- **max:** Valor máximo de los elementos
- **argmin:** Índice del valor mínimo
- **argmax:** Índice del valor máximo
- **cumsum:** Suma acumulada de los elementos
- **cumprod:** Producto acumulado de los elementos

In [17]:
array = np.random.randn(5,4)
array

array([[ 0.81837577, -0.44433379, -1.44851587, -2.53796668],
       [-1.07955993, -0.06931082,  2.28384433, -0.77471013],
       [-0.07690668,  0.0826777 , -0.15326353, -1.50374004],
       [-2.38307435, -2.13841739, -0.37191721,  1.45958387],
       [-1.45338076,  0.10811744, -0.77446782,  0.99624914]])

In [18]:
array = np.random.randn(5,4)
array

array([[ 0.89033132,  0.11333839,  1.06257441, -0.9742079 ],
       [-2.29176869,  0.7071412 , -0.74824422, -0.18396436],
       [ 0.54431595, -0.48842897, -1.46301326, -1.03398561],
       [-0.5512733 , -1.02313113, -0.16529772, -0.54416523],
       [ 0.66114298,  1.93584032,  0.03397144, -0.70004155]])

In [19]:
# Operación global
np.sum(array)

np.float64(-4.218865930070056)

In [20]:
# Operación por columnas
np.sum(array, axis=0)

array([-0.74725175,  1.24475982, -1.28000935, -3.43636465])

In [21]:
# Operaciones por filas
np.sum(array, axis=1)

array([ 1.09203622, -2.51683606, -2.44111189, -2.28386739,  1.93091319])

In [22]:
array.sum()

np.float64(-4.218865930070056)

In [23]:
np.argmax(array)

np.int64(17)

In [24]:
np.argmin(array)

np.int64(4)

In [25]:
np.cumsum(array)

array([ 0.89033132,  1.00366971,  2.06624412,  1.09203622, -1.19973247,
       -0.49259127, -1.24083549, -1.42479984, -0.88048389, -1.36891287,
       -2.83192613, -3.86591173, -4.41718503, -5.44031616, -5.60561389,
       -6.14977912, -5.48863614, -3.55279582, -3.51882438, -4.21886593])

In [26]:
np.cumprod(array)

array([ 8.90331320e-01,  1.00908718e-01,  1.07223021e-01, -1.04457514e-01,
        2.39392461e-01,  1.69284273e-01, -1.26665979e-01,  2.33020252e-02,
        1.26836640e-02, -6.19506900e-03,  9.06346809e-03, -9.37149554e-03,
        5.16625530e-03, -5.28575661e-03,  8.73723531e-04, -4.75449969e-04,
       -3.14340407e-04, -6.08512836e-04, -2.06720592e-05,  1.44713005e-05])

In [27]:
array = np.random.randn(5, 5)
array

array([[-0.22845334, -0.49326747,  1.78701058,  2.06387964,  0.17519315],
       [-0.8371127 , -1.11085089, -0.67918091, -0.56853014,  0.99559436],
       [-0.02338853, -0.0599453 , -0.95138683, -1.07920203,  0.08625623],
       [ 0.16531062,  0.10566658,  1.32042608,  0.07194379, -1.1263263 ],
       [-1.13166856,  0.20300967, -0.21950877,  2.05075235,  0.24139299]])

In [28]:
# Elementos mayores que 0
(array > 0).sum()

np.int64(12)

In [29]:
# Elementos mayores que la media
(array < array.mean()).sum()

np.int64(13)

In [30]:
# Algunos de los elementos cumple la condición
(array == 0).any()

np.False_

In [31]:
# Todos lo elementos cumple la condición
((array >= -2) & (array <= 2)).all()

np.False_

In [32]:
array = np.random.randn(5, 5)
array

array([[ 0.87039929, -0.08709707, -0.11188016,  0.88551135, -1.12669532],
       [-0.39660017, -1.20742511,  0.58088083,  0.43320969,  0.1393577 ],
       [-0.07209844, -0.00324558,  0.14076135,  1.91673613,  1.29312667],
       [-0.51078148,  1.29413241, -1.06721938,  2.82122104, -1.32481968],
       [ 0.35684488,  0.26682475,  1.51509264, -0.25212183, -1.40849978]])

In [33]:
# Datos ordenados
np.sort(array)

array([[-1.12669532, -0.11188016, -0.08709707,  0.87039929,  0.88551135],
       [-1.20742511, -0.39660017,  0.1393577 ,  0.43320969,  0.58088083],
       [-0.07209844, -0.00324558,  0.14076135,  1.29312667,  1.91673613],
       [-1.32481968, -1.06721938, -0.51078148,  1.29413241,  2.82122104],
       [-1.40849978, -0.25212183,  0.26682475,  0.35684488,  1.51509264]])

In [34]:
# Datos ordenados según el primer eje
np.sort(array, axis = 0)

array([[-0.51078148, -1.20742511, -1.06721938, -0.25212183, -1.40849978],
       [-0.39660017, -0.08709707, -0.11188016,  0.43320969, -1.32481968],
       [-0.07209844, -0.00324558,  0.14076135,  0.88551135, -1.12669532],
       [ 0.35684488,  0.26682475,  0.58088083,  1.91673613,  0.1393577 ],
       [ 0.87039929,  1.29413241,  1.51509264,  2.82122104,  1.29312667]])

- **unique:** Calcula el conjunto único de elementos sin duplicados.
- **intersect1d:** Calcula la intersección de los elementos de dos arrays.
- **union1d:** Calcula la unión de los elementos de dos arrays.
- **in1d:** Calcula un array booleano que indica si cada elemento del primer array contenido en el segundo.
- **setdiff1d:** Calcula la diferencia entre ambos conjuntos.
- **setxor1d:** Calcula la diferencia simétrica entre ambos conjuntos.

In [35]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [36]:
array2= np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [37]:
np.unique(array1)

array([0, 2, 3, 5, 6])

In [38]:
np.union1d(array1, array2)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
np.in1d(array1, array2)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_23548\1784259358.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(array1, array2)


array([ True, False, False, False,  True,  True,  True,  True])